# Site settings
title: Design Starter Kit
description: > # this means to ignore newlines until "baseurl:"
 A Design starter kit for students at The Iron Yard.
baseurl: "/design-starter-kit" # the subpath of your site, e.g. /blog/
url: "http://samkap.github.io" # the base hostname & protocol for your site
twitter_username: samkap
github_username:  samkap

# Build settings
markdown: kramdown
